<% app_domain = ENV.fetch("GOVUK_APP_DOMAIN", "") %>
<% env = %w(integration staging).detect { |s| app_domain.include?(s) } %>
<% email_subject_prefix = "#{env.upcase} - " if env %>
<% expect_status_update_callbacks = !env %>

default: &default
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "PSEUDO" %>
  email_subject_prefix: <%= email_subject_prefix %>
  email_address_override: <%= ENV["EMAIL_ADDRESS_OVERRIDE"] %>
  email_address_override_whitelist:
    <% whitelist = ENV.fetch("EMAIL_ADDRESS_OVERRIDE_WHITELIST", "").split(",").map(&:strip) %>
    <% whitelist.each do |email| %>
      - <%= email %>
    <% end %>

development:
  <<: *default
  expect_status_update_callbacks: false

test:
  <<: *default
  expect_status_update_callbacks: true

production:
  <<: *default
  expect_status_update_callbacks: <%= expect_status_update_callbacks %>
