development:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "PSEUDO" %>

test:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "PSEUDO" %>

production:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "NOTIFY" %>
