development:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "PSEUDO" %>
  email_address_override: <%= ENV["EMAIL_ADDRESS_OVERRIDE"] %>

test:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "PSEUDO" %>
  email_address_override: <%= ENV["EMAIL_ADDRESS_OVERRIDE"] %>

production:
  provider: <%= ENV["EMAIL_SERVICE_PROVIDER"] || "NOTIFY" %>
  email_address_override: <%= ENV["EMAIL_ADDRESS_OVERRIDE"] %>
