gov_delivery:
  username: gov-delivery+staging@digital.cabinet-office.gov.uk
  password: nottherealpassword
  account_code: UKGOVUK
  protocol: https
  hostname: stage-api.govdelivery.com
  subscription_link_template: https://stage-public.govdelivery.com/accounts/UKGOVUK/subscriber/new?topic_id=%{topic_id}
