development:
  username: govdelivery@example.com
  password: nottherealpassword
  account_code: UKGOVUK
  protocol: https
  hostname: stage-api.govdelivery.com
  public_hostname: stage-public.govdelivery.com

test:
  username: test@example.com
  password: test123
  account_code: UKGOVUK
  protocol: http
  hostname: govdelivery-api.example.com
  public_hostname: govdelivery-public.example.com
