development:
  api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>
  template_id: <%= ENV['GOVUK_NOTIFY_TEMPLATE_ID'] || "a5583ad3-adab-4c76-b85d-f88bd4a3dc69" %>

test:
  api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>
  template_id: <%= ENV['GOVUK_NOTIFY_TEMPLATE_ID'] || "a5583ad3-adab-4c76-b85d-f88bd4a3dc69" %>

production:
  api_key: <%= ENV['GOVUK_NOTIFY_API_KEY'] %>
  template_id: <%= ENV['GOVUK_NOTIFY_TEMPLATE_ID'] %>
