---
:verbose: true
:concurrency: 30
:logfile: ./log/sidekiq.json.log
:queues:
  - [high_delivery, 3]
  - [low_delivery, 2]
  - [default, 1]
:schedule:
  immediate_email_generation:
    every: '5s'
    class: ImmediateEmailGenerationWorker
  daily_digest_initiator:
    cron: '30 8 * * *' # every day at 8:30am
    class: DailyDigestInitiatorWorker
  weekly_digest_initiator:
    cron: '30 8 * * 6' # every Saturday at 8:30am
    class: WeeklyDigestInitiatorWorker
