---
:verbose: true
:concurrency: 30
:logfile: ./log/sidekiq.json.log
:queues:
  - [high_delivery, 3]
  - [low_delivery, 2]
  - [default, 1]
:schedule:
  email_generation:
    every: '5s'
    class: EmailGenerationWorker
