---
:verbose: true
:concurrency: 30
:logfile: ./log/sidekiq.json.log
:queues:
  - govdelivery
  - [delivery_immediate_high, 6]
  - [delivery_immediate, 5]
  - [email_generation_immediate, 4]
  - [default, 3]
  - [delivery_digest, 2]
  - [email_generation_digest, 1]
:schedule:
  immediate_email_generation:
    every: '5s'
    class: ImmediateEmailGenerationWorker
