---
:verbose: true
:concurrency: 30
:logfile: ./log/sidekiq.json.log
:queues:
  - govdelivery
  - [delivery_immediate_high, 6]
  - [delivery_immediate, 5]
  - [email_generation_immediate, 4]
  - [default, 3]
  - [delivery_digest, 2]
  - [email_generation_digest, 1]
  - cleanup
:schedule:
  immediate_email_generation:
    every: '5s'
    class: ImmediateEmailGenerationWorker
  daily_digest_initiator:
    cron: '30 8 * * *' # every day at 8:30am
    class: DailyDigestInitiatorWorker
  weekly_digest_initiator:
    cron: '30 8 * * 6' # every Saturday at 8:30am
    class: WeeklyDigestInitiatorWorker
  nullify_deactivated_subscribers:
    every: '1h'
    class: NullifyDeactivatedSubscribersWorker
